# Compilateur
CC = g++

# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -g -Wall

# Construit la cible executable:
TARGET = myprog

all: $(TARGET)

$(TARGET): $(TARGET).cpp
  	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	$(RM) $(TARGET)
